services:

  api:
    build: .

    container_name: reportly_api

    ports:
      - "8000:8000"

    depends_on:
      - redis

    volumes:
      - .:/app

    command: >
      uv run uvicorn api:app
      --host 0.0.0.0
      --port 8000


  worker:
    build: .

    container_name: reportly_worker

    depends_on:
      - redis

    volumes:
      - .:/app

    command: >
      uv run celery
      -A src.celery_worker.celery_app
      worker
      --loglevel=info


  redis:
    image: redis:7-alpine

    container_name: reportly_redis

    ports:
      - "6379:6379"